### PR TITLE
partially implement flexSearch for internal-db

### PR DESCRIPTION
**Pull request by mfusser**
did not implement:
- aggregations
- exist query (will implement this later if needed)
- fullTextQueries

### CODE REVIEW

**Comment by Yogu** [comment]
that was quick. Maybe you can enable some regression tests for in-memory now? Maybe split if the tests contain stuff that works and stuff that does not work

**Comment by mfusser** [comment]
> that was quick. Maybe you can enable some regression tests for in-memory now? Maybe split if the tests contain stuff that works and stuff that does not work

i updated the tests.
this will slow down the arangoDb tests by one second because of "waitForArangoSearch", but i guess that is ok.
I disabled the "waitForArangoSearch"

**Comment by Yogu** [comment]
strange, the test fails for 3.2 even though it should be ignored

**Comment by Yogu** [comment]
ah no the in-memory test failed in the execution that happened to have ArangoDB 3.2 installed. Maybe it just happens sometimes? https://github.com/AEB-labs/cruddl/pull/157/checks?check_run_id=750476526

**Comment by mfusser** [comment]
> ah no the in-memory test failed in the execution that happened to have ArangoDB 3.2 installed. Maybe it just happens sometimes? https://github.com/AEB-labs/cruddl/pull/157/checks?check_run_id=750476526

running the tests again made the error disappear. i will look at it again

**Pull request merged**
